src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LogoURL__c</fullName>
        <label>ロゴURL</label>
        <type>Url</type>
    </fields>
</CustomObject>

src/objects/JobApplicant__c.object
<CustomObject>
    <fields>
        <fullName>JobOpening__c</fullName>
        <label>人材募集</label>
        <referenceTo>JobOpening__c</referenceTo>
        <relationshipLabel>求職者</relationshipLabel>
        <relationshipName>JobApplicant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>求職者</label>
    <nameField>
        <displayFormat>求職者-{000000}</displayFormat>
        <label>求職者番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JobOpening__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>企業</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>人材募集</relationshipLabel>
        <relationshipName>JobOpening</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>概要</label>
        <type>TextArea</type>
    </fields>
    <label>人材募集</label>
    <nameField>
        <label>人材募集 タイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JobController.cls
global class JobController{
    public JobController(){
    
    }
    @RemoteAction
    global static List<JobOpening__c> getJobOpeningsList() {
        return [select Id, Name, Account__c, Account__r.Name, Account__r.LogoURL__c, Summary__c, LastModifiedDate from JobOpening__c where IsValid__c = true order by LastModifiedDate desc];
    }
    @RemoteAction
    global static Boolean applyForJob(JobApplicant__c applicant) {
        try{
            upsert applicant;
            return true;
        }catch(Exception e){
            System.debug('Error in applyForJob' + e);
        }
        return false;
    }
}