src/objects/Alert__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>内容</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsValid__c</fullName>
        <defaultValue>true</defaultValue>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <label>警報</label>
    <nameField>
        <displayFormat>警報-{000000}</displayFormat>
        <label>警報番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>内容</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsEvacuationCenter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>避難場所</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>電話番号</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShortDescription__c</fullName>
        <label>概要</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>種類</label>
        <picklist>
            <picklistValues>
                <fullName>海岸</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>レストラン</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ホームセンター</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>図書館</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>イベント施設</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>学校</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>場所</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SafetyStatus__c.object
<CustomObject>
    <fields>
        <fullName>Alert__c</fullName>
        <label>警告</label>
        <referenceTo>Alert__c</referenceTo>
        <relationshipName>SafetyNotice</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>安否状況</label>
    <nameField>
        <displayFormat>安否確認-{000000}</displayFormat>
        <label>安否確認</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AlertController.cls
global class AlertController{
    
    public AlertController(){

    }
    
    @RemoteAction
    global static List<Alert__c> getAlertList() {
        return [select Id, Name, Description__c, LastModifiedDate from Alert__c where IsValid__c = true order by LastModifiedDate desc];
    }
    @RemoteAction
    global static List<Location__c> getEvacuationList() {
        return [select Id, Name, Phone__c, ShortDescription__c, Type__c, Geolocation__latitude__s, Geolocation__longitude__s from Location__c where IsEvacuationCenter__c = true order by Name];
    }
    @RemoteAction
    global static boolean sendHelpNotice(SafetyStatus__c helpNotice) {
        try{
            upsert helpNotice;
        }catch(Exception e){
            System.debug(e);
            return false;
        }
        return true;
    }
    @RemoteAction
    global static boolean sendSafetyNotice(SafetyStatus__c safetyNotice) {
        try{
            upsert safetyNotice;
        }catch(Exception e){
            System.debug(e);
            return false;
        }
        return true;
    }
}