src/objects/Alert__c.object
<CustomObject>
    <fields>
        <fullName>IsValid__c</fullName>
        <defaultValue>true</defaultValue>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <label>警報</label>
    <nameField>
        <displayFormat>警報-{000000}</displayFormat>
        <label>警報番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDateTime__c</fullName>
        <label>イベント日時</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>スポンサー代表</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>イベント</relationshipLabel>
        <relationshipName>VolunteerEvent</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>概要</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>イベント</label>
    <nameField>
        <label>イベント名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JobApplicant__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>求職者</label>
        <referenceTo>User</referenceTo>
        <relationshipName>JobApplication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobOpening__c</fullName>
        <label>人材募集</label>
        <referenceTo>JobOpening__c</referenceTo>
        <relationshipLabel>求職者</relationshipLabel>
        <relationshipName>JobApplicant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>求職者</label>
    <nameField>
        <displayFormat>求職者-{000000}</displayFormat>
        <label>求職者番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JobOpening__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>企業</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>人材募集</relationshipLabel>
        <relationshipName>JobOpening</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsValid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>概要</label>
        <type>TextArea</type>
    </fields>
    <label>人材募集</label>
    <nameField>
        <label>人材募集 タイトル</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Participant__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>イベント</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>参加者</relationshipLabel>
        <relationshipName>VolunteerParticipant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ParticipantUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipName>VolunteerParticipant</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>参加者</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SafetyStatus__c.object
<CustomObject>
    <fields>
        <fullName>Alert__c</fullName>
        <label>警告</label>
        <referenceTo>Alert__c</referenceTo>
        <relationshipName>SafetyNotice</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SafetyNotice</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>安否状況</label>
    <nameField>
        <displayFormat>安否確認-{000000}</displayFormat>
        <label>安否確認</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Namie1Test.cls
@isTest 
private class Namie1Test {

    static testMethod void namie1Test() {
        //AlertController
        alertTest();
        
        //JobController
        jobTest();
        
        //NewsController
        newsTest();
        
        //EventController
        eventTest();
    }
    
    private static void alertTest() {
        Alert__c alert = new Alert__c(IsValid__c=true);
        upsert alert;
        AlertController alertCtrl = new AlertController();
        AlertController.getAlertList();
        AlertController.getEvacuationList();
        AlertController.sendHelpNotice(new SafetyStatus__c(Alert__c=alert.Id, User__c=UserInfo.getUserId()));
        AlertController.sendSafetyNotice(new SafetyStatus__c(Alert__c=alert.Id, User__c=UserInfo.getUserId()));
        
        //alert controller exception test
        AlertController.sendSafetyNotice(new SafetyStatus__c(User__c=UserInfo.getUserId()));
        AlertController.sendHelpNotice(new SafetyStatus__c(User__c=UserInfo.getUserId()));
    }

    private static void jobTest() {
        Account account = new Account(name='SFDC');
        upsert account;
        JobOpening__c jobOpening = new JobOpening__c(Name='sse', Account__c=account.Id, IsValid__c=true);
        upsert jobOpening;
        JobController jobCtrl = new JobController();
        JobController.getJobOpeningsList();
        JobController.applyForJob(new JobApplicant__c(JobOpening__c=jobOpening.Id, Applicant__c=UserInfo.getUserId()));
        
        //job controller exception test
        JobController.applyForJob(new JobApplicant__c(Applicant__c=UserInfo.getUserId()));
    }

    private static void newsTest() {
        NewsController newsCtrl = new NewsController();
        NewsController.getNewsList();
    }
    
    private static void eventTest() {
        Account account = new Account(Name='SFDC');
        upsert account;
        Contact contact = new COntact(LastName='R R', AccountId=account.Id);
        upsert contact;
        Event__c event = new Event__c(name='テスト', ActivityDateTime__c=Date.Today(), Summary__c='something fun for everyone!', Organizer__c=contact.Id);
        upsert event;
        
        EventController eventCtrl = new EventController();
        EventController.getUpcomingVolunteerList();
        EventController.joinEvent(new Participant__c(Event__c=event.Id, ParticipantUser__c=UserInfo.getUserId()));
        EventController.queryCalendar(String.valueOf(Date.Today()));
        EventController.queryEventOnDay(String.valueOf(Date.Today()));
        //event controller exception test
        EventController.joinEvent(new Participant__c(ParticipantUser__c=UserInfo.getUserId()));
    }

    
}